### ISSUE TITLE
startlxde throws 'No session for pid' error

### ISSUE THREAD

**Issue by ghost** [WhitewaterFoundry/Pengwin#429]
After doing `sudo apt-get install task-lxde-desktop` and then `startlxde`, the desktop environment does successfully start, but it throws this error every time:

![image](https://user-images.githubusercontent.com/37132025/56453011-24334380-6300-11e9-82ae-b7405a3cc7f2.png)

**Comment by Aidolii** [comment]
Also happens in Windowed Apps mode.

**Comment by sirredbeard** [comment]
`sudo apt-get install task-lxde-desktop` is installing something with a service dependency, probably dbus.

Just use `sudo apt-get install lxde` which will get you started without this error. You can install Synaptic with `sudo apt-get install synaptic` to get a graphical package manager.

You can launch dbus manually by `sudo apt-get install dbus-x11` and then run `dbus launch`. This is in the pipeline to be added as a feature.

**Comment by Aidolii** [comment]
Did a completely fresh installation. Uninstalled Pengwin, reinstalled it. Did pengwin-setup and the only thing I did was Tools > GUI. Then I did sudo apt update, sudo apt upgrade, and lastly, sudo apt-get install lxde. Then I did startlxde. Same thing happened.

![image](https://user-images.githubusercontent.com/37132025/56454154-3f0eb380-6312-11e9-8804-aecb11e20653.png)

Then I did sudo apt install dbus-x11, it installs the package successfully. Did dbus launch. Nothing.

![image](https://user-images.githubusercontent.com/37132025/56454182-914fd480-6312-11e9-8f4a-6cf8068b7e68.png)

**Comment by sirredbeard** [comment]
I am currenty unable to duplicate. Can you `$ ps -p 16206 -o comm=` (replacing the PID as appropriate) next time this hapens?

Thanks.

**Comment by Aidolii** [comment]
The return is `lxpolkit`

**Comment by Aidolii** [comment]
Fixed it by going to Preferences > Default applications for LXSession > Core applications, and then clearing the Polkit agent field.

!()[https://i.imgur.com/WBocYTd.gif]

**Comment by jackghg** [comment]
> Fixed it by...
Are you saying that lxpolkit is useless ?

**Comment by crramirez** [comment]
This issue was closed three years ago, before WSL2. You can try now for WSL2 if this workaround is still needed

**Comment by kupietools** [comment]
Actually according to an answer on Stack Exchange (which I now can't find but just saw it), lxpolkit is required if you want to be able to run Synaptic from the menu. So, if everybody is to be believed, it is required that you both use and do not us lxpolkit.

This is a _wonderful_ system.

**Comment by Nandita-Chaudhuri** [comment]
No session for pid' error  still persists for me using WSL2
![error1](https://github.com/WhitewaterFoundry/Pengwin/assets/159573903/80907379-57e9-4bc9-b154-07010f381cbb)
![Screenshot 2024-04-14 013225](https://github.com/WhitewaterFoundry/Pengwin/assets/159573903/3540d401-ace7-4adc-ba6f-bcc2edaa6ee9)
![Screenshot 2024-04-14 013251](https://github.com/WhitewaterFoundry/Pengwin/assets/159573903/6d04c3c7-ea57-413c-8843-ffad477de680)
Kindly help me on this

**Comment by crramirez** [comment]
Did you try this workaround? https://github.com/WhitewaterFoundry/Pengwin/issues/429#issuecomment-485259611
